# Example requests for the API
# You can use an extension like REST Client to run these directly in VSCode

# Bloodbath example
GET http://localhost:8048/list?levelid=10565740&platformer=false&response=csv HTTP/1.1

###

GET http://localhost:8048/analysis?levelid=10565740&response=csv HTTP/1.1

###

POST http://localhost:8048/submit HTTP/1.1
content-type: application/json

{
    "format": 1,
    "levelid": 10565740,
    "levelversion": 0,
    "practice": false,
    "playername": "RobTop",
    "userid": 16,
    "x": 3454.12812,
    "y": 423.55915,
    "percentage": 56
}

###

# Excluded Level example
GET http://localhost:8048/list?levelid=69069068&platformer=false&response=csv HTTP/1.1

###

POST http://localhost:8048/submit HTTP/1.1
content-type: application/json

{
    "format": 1,
    "levelid": 69069068,
    "levelversion": 0,
    "practice": false,
    "playername": "RobTop",
    "userid": 16,
    "x": 3454.12812,
    "y": 423.55915,
    "percentage": 56
}